info:
  client: samples
  project: springboot-maven
  environment: dev
metadata:
  PROJECT_WORKSPACE: springboot-maven
  COMPUTE_TYPE: small
source:
  type: CodeStar
  codeStar:
    branch: main
    repository: mrwconsulting/shinto-samples
    codeStarArn: >-
      arn:aws:codestar-connections:us-east-1:578205859804:connection/d40b135b-3d77-4c5c-8330-2f575fba9998
stages:
  - stageName: BuildStage
    stageType: pre
    pluginName: 21-Corretto
    metadata:
      '21-CORRETTO:PRIVILEGED': 'true'
    commands:
      - echo "********* BuildStage ***********"
      - mvn --version
    variables:
      MY_VAR:
        value: HELLO-WORLD
      ANOTHER_VAR:
        type: PLAINTEXT
        value: HELLO-WORLD
    partialBuildSpecFile: yaml/exported-variables.yaml
    post:
      - pluginName: 3.19-Alpine
        commands:
          - echo "********* ADD-ON ***********"
      - pluginName: 3.19-Alpine
        commands:
          - echo "********* ANOTHER ADD-ON ***********"
  - stageName: AnotherStage
    stageType: post
    pluginName: 21-Corretto
    pluginAliasName: Linux
    metadata:
      '21-CORRETTO:PRIVILEGED': 'false'
    commands:
      - echo "********* AnotherStage ***********"
      - echo ${CODEBUILD_ANOTHER_VAR} ${ANOTHER_VAR_STAGE}
      - mvn --version
    variables:
      MY_VAR_STAGE:
        value: #{Variables.MY_VAR}
      ANOTHER_VAR_STAGE:
        value: ${CODEBUILD_ANOTHER_VAR}
    partialBuildSpecFile: yaml/reports.yaml
    pre:
      - pluginName: 3.19-Alpine
        pluginAliasName: Linux-01
        commands:
          - echo "********* ADD-ON ***********"
      - pluginName: 3.19-Alpine
        pluginAliasName: Linux-02
        commands:
          - echo "********* ANOTHER ADD-ON ***********"
