info:
  client: samples
  project: springboot-maven
  environment: dev
metadata:
  PROJECT_WORKSPACE: springboot-maven
  COMPUTE_TYPE: small
source:
  type: CodeStar
  codeStar:
    branch: main
    repository: mrwconsulting/shinto-samples
    codeStarArn: >-
      arn:aws:codestar-connections:us-east-1:578205859804:connection/d40b135b-3d77-4c5c-8330-2f575fba9998
stages:
  - stageName: BuildStage
    stepType: pre
    pluginName: 21-Corretto
    metadata:
      '21-CORRETTO:PRIVILEGED': 'true'
    commands:
      - echo "********* hello world ***********"
      - mvn --version
    variables:
      MY_VAR:
        value: HELLO-WORLD
      ANOTHER_VAR:
        type: PLAINTEXT
        value: HELLO-WORLD
    partialBuildSpecFile: 'yaml/exported-variables.yaml'