info:
  client: samples
  project: springboot-maven
  environment: dev
metadata:
  PROJECT_WORKSPACE: springboot-maven
  COMPUTE_TYPE: small
source:
  type: CodeStar
  codeStar:
    branch: main
    repository: mrwconsulting/shinto-samples
    codeStarArn: >-
      arn:aws:codestar-connections:us-east-1:578205859804:connection/d40b135b-3d77-4c5c-8330-2f575fba9998
stages:
  - stageName: BuildStage
    stageType: pre
    pluginName: 21-Corretto
    pluginAliasName: OpenJDK
    metadata:
      '21-CORRETTO:PRIVILEGED': 'false'
    outputDirectory:
      - target
    commands:
      - ./mvnw clean install compile package
    partialBuildSpecFile: yaml/reports.yaml
  - stageName: MyStage
    stageType: pre
    pluginName: UnixShell
    pluginAliasName: Bash
    commands:
      - echo "********* MyStage ***********"
      - pwd & ls -l
      - ls -l target/*
    mappings:
      'BuildStage:OpenJDK':
        - type: output-directory
          value: target