info:
  client: samples
  project: springboot-maven
  environment: dev
metadata:
  PROJECT_WORKSPACE: springboot-maven
  COMPUTE_TYPE: small
source:
  type: CodeStar
  codeStar:
    branch: main
    repository: mrwconsulting/shinto-samples
    codeStarArn: >-
      arn:aws:codestar-connections:us-east-1:578205859804:connection/d40b135b-3d77-4c5c-8330-2f575fba9998
stages:
  - stageName: BuildStage
    stageType: pre
    metadata:
      '21-CORRETTO:PRIVILEGED': 'true'
    pluginName: 21-Corretto
    pluginAliasName: OpenJDK
    outputDirectory:
      - springboot-maven/dist
    commands:
      - echo "********* BuildStage ***********"
      - mvn --version
      - mkdir dist && echo "hello-world" >> dist/notes.txt
      - cat dist/notes.txt
      - pwd && ls -l
    variables:
      MY_VAR:
        value: HELLO-WORLD
      ANOTHER_VAR:
        type: PLAINTEXT
        value: HELLO-WORLD
    partialBuildSpecFile: yaml/exported-variables.yaml
    post:
      - pluginName: 3.19-Alpine
        commands:
          - echo "********* ADD-ON ***********"
      - pluginName: 3.19-Alpine
        commands:
          - echo "********* ANOTHER ADD-ON ***********"
  - stageName: AnotherStage
    stageType: post
    pluginName: 21-Corretto
    pluginAliasName: Bash
    outputDirectory:
      - lib
    commands:
      - echo "********* AnotherStage ***********"
      - env
      - 'echo ${PIPELINE_ID}'
    mappings:
      'BuildStage:OpenJDK': 
        output-directory : dist
