info:
  client: samples
  project: springboot-maven
  environment: dev
metadata:
  PROJECT_WORKSPACE: springboot-maven
  COMPUTE_TYPE: small
source:
  type: CodeStar
  codeStar:
    branch: main
    repository: mrwconsulting/shinto-samples
    codeStarArn: >-
      arn:aws:codestar-connections:us-east-1:578205859804:connection/d40b135b-3d77-4c5c-8330-2f575fba9998
stages:
  - stageName: BuildStage
    stageType: pre
    pluginName: 21-Corretto
    pluginAliasName: OpenJDK
    metadata:
      '21-CORRETTO:PRIVILEGED': 'false'
    outputDirectory:
      - springboot-maven/dist
    commands:
      - echo "********* BuildStage ***********"
      - mvn --version
      - mkdir dist && echo "hello-world" >> dist/notes.txt
      - cat dist/notes.txt
      - pwd && ls -l
    variables:
      MY_VAR:
        value: HELLO-WORLD
      ANOTHER_VAR:
        type: PLAINTEXT
        value: HELLO-WORLD
    partialBuildSpecFile: yaml/exported-variables.yaml
    post:
      - pluginName: 3.19-Alpine
        pluginAliasName: Alpine-01
        commands:
          - echo "********* ADD-ON ***********"
      - pluginName: 3.19-Alpine
        pluginAliasName: Alpine-02
        commands:
          - echo "********* ANOTHER ADD-ON ***********"
  - stageName: MyStage
    stageType: pre
    pluginName: UnixShell
    pluginAliasName: Bash
    metadata:
      'UNIXSHELL:PRIVILEGED': 'true'
    commands:
      - echo "********* MyStage ***********"
    mappings:
      'BuildStage:OpenJDK':
        - type: exported-variable
          value: MY_VAR
        - type: exported-variable
          value: ANOTHER_VAR
        - type: output-directory
          value: dist
    post:
      - pluginName: 3.19-Alpine
        pluginAliasName: Alpine-01
        commands:
          - echo "********* ADD-ON ***********"
        mappings:
          'BuildStage:OpenJDK':
            - type: exported-variable
              value: MY_VAR
            - type: exported-variable
              value: ANOTHER_VAR
            - type: output-directory
              value: dist
      - pluginName: 3.19-Alpine
        pluginAliasName: Alpine-02
        commands:
          - echo "********* ANOTHER ADD-ON ***********"
        mappings:
          'BuildStage:OpenJDK':
            - type: exported-variable
              value: MY_VAR
            - type: exported-variable
              value: ANOTHER_VAR
            - type: output-directory
              value: dist
  - stageName: AnotherStage
    pluginName: 3.19-Alpine
    pluginAliasName: Bash
    metadata:
      '3.19-ALPINE:PRIVILEGED': 'true'
    commands:
      - echo "********* AnotherStage ***********"
    mappings: null
    'BuildStage:OpenJDK':
      - type: exported-variable
        value: MY_VAR
      - type: exported-variable
        value: ANOTHER_VAR
      - type: output-directory
        value: dist
    pre:
      - pluginName: 3.19-Alpine
        pluginAliasName: Alpine-01
        commands:
          - echo "********* ADD-ON ***********"
        mappings:
          'BuildStage:OpenJDK':
            - type: exported-variable
              value: MY_VAR
            - type: exported-variable
              value: ANOTHER_VAR
            - type: output-directory
              value: dist
      - pluginName: 3.19-Alpine
        pluginAliasName: Alpine-02
        commands:
          - echo "********* ANOTHER ADD-ON ***********"
        mappings:
          'BuildStage:OpenJDK':
            - type: exported-variable
              value: MY_VAR
            - type: exported-variable
              value: ANOTHER_VAR
            - type: output-directory
              value: dist
