info:
  client: samples
  project: springboot-maven
metadata:
  PROJECT_WORKSPACE: springboot-maven
  COMPUTE_TYPE: small
source:
  type: CodeStar
  codeStar:
    branch: main
    repository: mrwconsulting/shinto-samples
    codeStarArn: >-
      arn:aws:codestar-connections:us-east-1:578205859804:connection/d40b135b-3d77-4c5c-8330-2f575fba9998
stages:
  - stageName: BuildStage
    pluginName: 3.9-Maven
    pluginAliasName: OpenJDK
    metadata:
      '3.9-MAVEN:PRIVILEGED': 'false'
    outputDirectory:
      - target
    commands:
      - ./mvnw clean install compile package
    partialBuildSpecFile: yaml/reports.yaml
    post:
      - pluginName: Snyk-Sast
        pluginAliasName: Snyk-SAST
        commands:
          - snyk auth ${SNYK_API_TOKEN}
          - snyk monitor --org=${SNYK_ORG_ID} --file=pom.xml
        mappings:
          'BuildStage:OpenJDK':
            - type: output-directory
              value: target
        variables:
          SNYK_ORG_ID:
            type: PLAINTEXT
            value: d765b93b-ebb4-47ea-80eb-8a877d364e4e
          SNYK_API_TOKEN:
            type: PLAINTEXT
            value: 324e8e61-fa8b-47f6-bd29-ff107f4827cb
      - pluginName: Codacy-Sast
        pluginAliasName: Codacy-SAST
        commands:
          - codacy-coverage-reporter report
        mappings:
          'BuildStage:OpenJDK':
            - type: output-directory
              value: target