info:
  client: samples
  project: springboot-rest
  environment: dev
metadata:
  PROJECT_WORKSPACE: springboot-rest
  COMPUTE_TYPE: small
source:
  type: CodeStar
  codeStar:
    branch: main
    repository: mrwconsulting/shinto-samples
    codeStarArn: >-
      arn:aws:codestar-connections:us-east-1:578205859804:connection/d40b135b-3d77-4c5c-8330-2f575fba9998
stages:
  - stageName: BuildStage
    stageType: pre
    pluginName: 21-Corretto
    pluginAliasName: OpenJDK
    metadata:
      '21-CORRETTO:PRIVILEGED': 'true'
    outputDirectory:
      - dist
    commands:
      - ./mvnw clean install compile package
  - stageName: MyStage
    stageType: pre
    pluginName: UnixShell
    pluginAliasName: Bash
    commands:
      - echo "********* MyStage ***********"
      - pwd & ls -l
  - stageName: AnotherStage
    pluginName: 3.19-Alpine
    pluginAliasName: Bash
    metadata:
      '3.19-ALPINE:PRIVILEGED': 'true'
    commands:
      - echo "********* AnotherStage ***********"